### ISSUE TITLE
Content doesn't open up for the first time

### ISSUE THREAD

**Issue by VijayaSankarN** [Bizcuit/vscode-ampscript#15]
Whenever VS Code is closed with a content builder content opened up, the next time when VS Code is opened that particulat file keeps loading. 

**Workaround** is to open the different content builder content, relaunch the VS Code.

**Comment by Bizcuit** [comment]
@VijayaSankarN This is going to be fixed in V3 release that is coming soon. 
As a temp workaround you can simply reconnect to the account and open a file again. To do that you need to do the right mouse click on the BU folder, then select "Remove from Workspace". Then open Connection Manager and connect back to the same BU.

**Comment by Bizcuit** [comment]
Hi @VijayaSankarN 
New version is now available. This issue should be fixed now + check all new features that are now available in the extension
