### ISSUE TITLE
how to pull more records from rows.csv 

### ISSUE THREAD

**Issue by newmanr19** [Bizcuit/vscode-ampscript#30]
sorry if not really an issue, but more of a feature/settings question.  When I open rows.csv for a large DE (2-3mil rows) I see that it pulls only the first 2k.  That is probably because of the 2k per minute limit that SFMC has on requests?..   so if I retrieve the data in to VS Code, I assume any filters or queries on that data, will be limited to that 2k worth of records?  any way around this?

**Comment by Bizcuit** [comment]
Hi @newmanr19 
This is because MC API returns a max of 2500 rows with one API call. There is a way to keep calling API until you get all records, but VS will crash at some point because of the volume of data. 
There is already a way to apply filters to the dataextension with SQL like queries. Try to find a blue filter button at the top right corner of the UI.
