### ISSUE TITLE
Connect to Shared Data Extensions

### ISSUE THREAD

**Issue by eva-armenteros-gc** [Bizcuit/vscode-ampscript#35]
Hi,
I am not able to access shared data extensions within MCFS after trying adding all kind of BU permissions to the installed package. Am I missing something? Is there any way of doing this?

Thanks!

**Comment by Bizcuit** [comment]
Hi @eva-armenteros-gc 
That's because shared dataextension were not supported until version 3.0.6 that I've just published. Give MS servers a few minutes to update the cache and update the extension to the latest version. 

Hi @carlsteinhilber, as far as I remember you were also waiting for this feature. 

PS: Shared dataextension are only available when you are connected to the Ent BU (top level BU).

Please let me know if everything works as expected and I'll close this Issue.

**Comment by eva-armenteros-gc** [comment]
Hi @Bizcuit, it worked!
Amazing, thanks for the swiftness.

**Comment by Bizcuit** [comment]
@eva-armenteros-gc 
Happy to hear that. If you like this extension, don't forget to leave your review on the [extension page](https://marketplace.visualstudio.com/items?itemName=sergey-agadzhanov.AMPscript&ssr=false#review-details)
